input.onPinPressed(TouchPin.P0, function () {
    basic.showString("" + (input.temperature()))
})
input.onLogoEvent(TouchButtonEvent.LongPressed, function () {
    basic.showString("" + (input.lightLevel()))
})
input.onButtonPressed(Button.A, function () {
    basic.showNumber(0)
    basic.showNumber(1)
    basic.showNumber(2)
    basic.showNumber(3)
    basic.showNumber(4)
    basic.showNumber(5)
    basic.showNumber(6)
    basic.showNumber(7)
    basic.showString("8")
    basic.showNumber(9)
    basic.showNumber(10)
    basic.showNumber(11)
    basic.showNumber(12)
    basic.showNumber(13)
    basic.showNumber(14)
    basic.showNumber(15)
    basic.showNumber(16)
    basic.showNumber(17)
    basic.showNumber(18)
    basic.showNumber(19)
    basic.showNumber(20)
    basic.showNumber(21)
    basic.showNumber(22)
    basic.showNumber(23)
    basic.showNumber(24)
    basic.showNumber(25)
    basic.showNumber(26)
    basic.showNumber(27)
    basic.showNumber(28)
    basic.showNumber(29)
    basic.showNumber(30)
    basic.showNumber(31)
    basic.showNumber(32)
    basic.showNumber(33)
    basic.showNumber(34)
    basic.showNumber(35)
    basic.showNumber(36)
    basic.showNumber(37)
    basic.showNumber(38)
    basic.showNumber(39)
    basic.showNumber(40)
    basic.showNumber(41)
    basic.showNumber(42)
    basic.showNumber(43)
    basic.showNumber(44)
    basic.showNumber(45)
    basic.showNumber(46)
    basic.showNumber(47)
    basic.showNumber(48)
    basic.showNumber(49)
    basic.showNumber(50)
    basic.showString("shake it realy hard for part 2")
})
input.onPinPressed(TouchPin.P2, function () {
    for (let index = 0; index < 30 * 2; index++) {
        music.setBuiltInSpeakerEnabled(true)
        music.setVolume(127)
        music.playMelody("C D E F G A B C5 ", 120)
    }
    music.setVolume(0)
})
input.onButtonPressed(Button.AB, function () {
    basic.showString("Hello this is the alphabet song!")
    basic.showString("Aa")
    basic.showString("Bb")
    basic.showString("Cc")
    basic.showString("Dd")
    basic.showString("Ee")
    basic.showString("Ff")
    basic.showString("Gg")
    basic.showString("Hh")
    basic.showString("Ii")
    basic.showString("Jj")
    basic.showString("Kk")
    basic.showString("Ll")
    basic.showString("Mm")
    basic.showString("Nn")
    basic.showString("Oo")
    basic.showString("Pp")
    basic.showString("Qq")
    basic.showString("Rr")
    basic.showString("Ss")
    basic.showString("Tt")
    basic.showString("Uu")
    basic.showString("Vv")
    basic.showString("Ww")
    basic.showString("Xx")
    basic.showString("Yy")
    basic.showString("Zz")
    basic.showString("These are the combined letters")
    basic.showString("Ay ay")
    basic.showString("Ee ee")
    basic.showString("OO oo")
})
input.onButtonPressed(Button.B, function () {
    basic.showNumber(randint(2, 12))
})
input.onPinPressed(TouchPin.P1, function () {
    input.calibrateCompass()
    basic.showString("" + (input.compassHeading()))
    basic.showArrow(ArrowNames.North)
})
input.onGesture(Gesture.Shake, function () {
    basic.showNumber(51)
    basic.showNumber(52)
    basic.showNumber(53)
    basic.showNumber(54)
    basic.showNumber(55)
    basic.showNumber(56)
    basic.showNumber(57)
    basic.showNumber(58)
    basic.showNumber(59)
    basic.showNumber(60)
    basic.showNumber(61)
    basic.showNumber(62)
    basic.showNumber(63)
    basic.showNumber(64)
    basic.showNumber(65)
    basic.showNumber(66)
    basic.showNumber(67)
    basic.showNumber(68)
    basic.showNumber(69)
    basic.showNumber(70)
    basic.showNumber(71)
    basic.showNumber(72)
    basic.showNumber(73)
    basic.showNumber(74)
    basic.showNumber(75)
    basic.showNumber(76)
    basic.showNumber(77)
    basic.showNumber(78)
    basic.showNumber(79)
    basic.showNumber(80)
    basic.showNumber(81)
    basic.showNumber(82)
    basic.showNumber(83)
    basic.showNumber(84)
    basic.showNumber(85)
    basic.showNumber(86)
    basic.showNumber(87)
    basic.showNumber(88)
    basic.showNumber(89)
    basic.showNumber(90)
    basic.showNumber(91)
    basic.showNumber(92)
    basic.showNumber(93)
    basic.showNumber(94)
    basic.showNumber(95)
    basic.showNumber(96)
    basic.showNumber(97)
    basic.showNumber(98)
    basic.showNumber(99)
    basic.showNumber(100)
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.showString("" + (input.soundLevel()))
})
