def on_pin_pressed_p0():
    basic.show_string("" + str(input.temperature()))
input.on_pin_pressed(TouchPin.P0, on_pin_pressed_p0)

def on_logo_long_pressed():
    basic.show_string("" + str(input.light_level()))
input.on_logo_event(TouchButtonEvent.LONG_PRESSED, on_logo_long_pressed)

def on_button_pressed_a():
    basic.show_number(0)
    basic.show_number(1)
    basic.show_number(2)
    basic.show_number(3)
    basic.show_number(4)
    basic.show_number(5)
    basic.show_number(6)
    basic.show_number(7)
    basic.show_string("8")
    basic.show_number(9)
    basic.show_number(10)
    basic.show_number(11)
    basic.show_number(12)
    basic.show_number(13)
    basic.show_number(14)
    basic.show_number(15)
    basic.show_number(16)
    basic.show_number(17)
    basic.show_number(18)
    basic.show_number(19)
    basic.show_number(20)
    basic.show_number(21)
    basic.show_number(22)
    basic.show_number(23)
    basic.show_number(24)
    basic.show_number(25)
    basic.show_number(26)
    basic.show_number(27)
    basic.show_number(28)
    basic.show_number(29)
    basic.show_number(30)
    basic.show_number(31)
    basic.show_number(32)
    basic.show_number(33)
    basic.show_number(34)
    basic.show_number(35)
    basic.show_number(36)
    basic.show_number(37)
    basic.show_number(38)
    basic.show_number(39)
    basic.show_number(40)
    basic.show_number(41)
    basic.show_number(42)
    basic.show_number(43)
    basic.show_number(44)
    basic.show_number(45)
    basic.show_number(46)
    basic.show_number(47)
    basic.show_number(48)
    basic.show_number(49)
    basic.show_number(50)
    basic.show_string("shake it realy hard for part 2")
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_pin_pressed_p2():
    for index in range(30 * 2):
        music.set_built_in_speaker_enabled(True)
        music.set_volume(127)
        music.play_melody("C D E F G A B C5 ", 120)
    music.set_volume(0)
input.on_pin_pressed(TouchPin.P2, on_pin_pressed_p2)

def on_button_pressed_ab():
    basic.show_string("Hello this is the alphabet song!")
    basic.show_string("Aa")
    basic.show_string("Bb")
    basic.show_string("Cc")
    basic.show_string("Dd")
    basic.show_string("Ee")
    basic.show_string("Ff")
    basic.show_string("Gg")
    basic.show_string("Hh")
    basic.show_string("Ii")
    basic.show_string("Jj")
    basic.show_string("Kk")
    basic.show_string("Ll")
    basic.show_string("Mm")
    basic.show_string("Nn")
    basic.show_string("Oo")
    basic.show_string("Pp")
    basic.show_string("Qq")
    basic.show_string("Rr")
    basic.show_string("Ss")
    basic.show_string("Tt")
    basic.show_string("Uu")
    basic.show_string("Vv")
    basic.show_string("Ww")
    basic.show_string("Xx")
    basic.show_string("Yy")
    basic.show_string("Zz")
    basic.show_string("These are the combined letters")
    basic.show_string("Ay ay")
    basic.show_string("Ee ee")
    basic.show_string("OO oo")
input.on_button_pressed(Button.AB, on_button_pressed_ab)

def on_button_pressed_b():
    basic.show_number(randint(2, 12))
input.on_button_pressed(Button.B, on_button_pressed_b)

def on_pin_pressed_p1():
    input.calibrate_compass()
    basic.show_string("" + str(input.compass_heading()))
    basic.show_arrow(ArrowNames.NORTH)
input.on_pin_pressed(TouchPin.P1, on_pin_pressed_p1)

def on_gesture_shake():
    basic.show_number(51)
    basic.show_number(52)
    basic.show_number(53)
    basic.show_number(54)
    basic.show_number(55)
    basic.show_number(56)
    basic.show_number(57)
    basic.show_number(58)
    basic.show_number(59)
    basic.show_number(60)
    basic.show_number(61)
    basic.show_number(62)
    basic.show_number(63)
    basic.show_number(64)
    basic.show_number(65)
    basic.show_number(66)
    basic.show_number(67)
    basic.show_number(68)
    basic.show_number(69)
    basic.show_number(70)
    basic.show_number(71)
    basic.show_number(72)
    basic.show_number(73)
    basic.show_number(74)
    basic.show_number(75)
    basic.show_number(76)
    basic.show_number(77)
    basic.show_number(78)
    basic.show_number(79)
    basic.show_number(80)
    basic.show_number(81)
    basic.show_number(82)
    basic.show_number(83)
    basic.show_number(84)
    basic.show_number(85)
    basic.show_number(86)
    basic.show_number(87)
    basic.show_number(88)
    basic.show_number(89)
    basic.show_number(90)
    basic.show_number(91)
    basic.show_number(92)
    basic.show_number(93)
    basic.show_number(94)
    basic.show_number(95)
    basic.show_number(96)
    basic.show_number(97)
    basic.show_number(98)
    basic.show_number(99)
    basic.show_number(100)
input.on_gesture(Gesture.SHAKE, on_gesture_shake)

def on_logo_pressed():
    basic.show_string("" + str(input.sound_level()))
input.on_logo_event(TouchButtonEvent.PRESSED, on_logo_pressed)
